//this variable will hold a random number generated by the random() function
float randomNumber;

//Set up - this is where you get things "set-up". It will only run once
void setup() {
  
  //setup serial communications through the USB
  Serial.begin(9600);

  //Randomise every time
  randomSeed(analogRead(0));   
      
}//close setup

void loop() {
  
  //generate a random number
  randomNumber = random(25.0,65.0);
  
  //display the random number on the serial monitor
  //Serial.print("The Random Number is = ");
  Serial.println(randomNumber);
  delay(1000);  
  
  //  Serial.write(randomNumber); // write the value to the serial port to be read
}